New commit

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -25,16 +25,16 @@ steps:
 
         apt update && apt install -y jq
         
-        #curl -s -X POST https://finance-app-back-end-911835065349.us-central1.run.app/generate_batch_summary \
-        #  -H "Content-Type: application/json" \
-        #  -d '{"input_filename": "test_cases.txt", "output_filename": "test_cases_processed_current"}' | jq -r '.' > /workspace/evaluation_response_current.json
+        curl -s -X POST https://finance-app-back-end-911835065349.us-central1.run.app/generate_batch_summary \
+          -H "Content-Type: application/json" \
+          -d '{"input_filename": "test_cases.txt", "output_filename": "test_cases_processed_current"}' | jq -r '.' > /workspace/evaluation_response_current.json
 
-        #cat /workspace/evaluation_response_current.json
+        cat /workspace/evaluation_response_current.json
 
-        #if [ "$(jq -r '.message' /workspace/evaluation_response_current.json)" != "Request was successful!" ]; then
-        #  echo "Error: The batch summary generation failed!"
-        #  exit 1
-        #fi
+        if [ "$(jq -r '.message' /workspace/evaluation_response_current.json)" != "Request was successful!" ]; then
+          echo "Error: The batch summary generation failed!"
+          exit 1
+        fi
 
         echo "The batch summary was generated successfully!"
 
